### ISSUE TITLE
accepts_nested_attributes_for

### ISSUE THREAD

**Issue by arta** [jeremydurham/custom-err-msg#1]
Hi,
your so greatly useful plugin doesn't seem to work with error messages on associated models' attributes nested through the accepts_nested_attributes_for. 
Rails 2.3.8, Ruby 1.8.7, MacOS X 10.6.4
thanks,
martin

**Comment by jeremydurham** [comment]
Sorry for the delay. I will resolve this shortly. I just added support for Rails3 (and accepts_nested_attributes_for in Rails3)

**Comment by jeremydurham** [comment]
I've pushed up code and specs that show this working in master.
