### ISSUE TITLE
 Rails 3 support breaks Rails 2 apps using authlogic

### ISSUE THREAD

**Issue by twalpole** [jeremydurham/custom-err-msg#2]
Since authlogic bases its Rails version detection on the presence of ActiveModel when getting the name of a class, defining ActiveModel in this gem in Rails 2 apps causes an issue.

**Comment by jeremydurham** [comment]
Split Rails 2 and Rails 3 extensions into ActiveRecord/ActiveModel. Closed by c39bbe84c59be43e058ca36e0251078dba3d263c

**Comment by twalpole** [comment]
Fixes that issue - thanks
