### ISSUE TITLE
generate_full_message fails with non-custom error message on Rails 2.3.10

### ISSUE THREAD

**Issue by twalpole** [jeremydurham/custom-err-msg#3]
When a non custom error message (not starting with ^) is passed to generate_full_message, keys is never set so the call to keys.shift in the I18N.translate call throws an error.

**Comment by jeremydurham** [comment]
Fixed generate_full_message broken in Rails 2.3.10. Closed by c6ffd53baeee93dc0e4bc6c368bf5af3fc2d0525
